=== AlexCanadas/DAM/LDM/Simulacro1/Ejercicio1/biblioteca.dtd
<!DOCTYPE biblioteca [
<!ELEMENT biblioteca (libro+)>
<!ELEMENT libro (titulo, autor, fechaPublicacion)>
<!ELEMENT titulo (#PCDATA)>

<!ELEMENT autor (nombre, fechaNacimiento?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT fechaNacimiento (#PCDATA)>

<!ELEMENT fechaPublicacion (año)>
<!ELEMENT año (#PCDATA)>
]>

=== AlexCanadas/DAM/LDM/Simulacro1/Ejercicio1/Ejercicio3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM "biblioteca.dtd">
<!-- Ejercicio 3 -->

<biblioteca>
    <libro>
        <titulo>La vida está en otra parte</titulo>
        <autor>
            <nombre>Milan Kundera</nombre>
        </autor>
        <fechaPublicacion>
            <anio>1973</anio>
        </fechaPublicacion>
    </libro>
    <libro>
        <titulo>Pantaleón y las visitadoras</titulo>
        <autor>
            <nombre>Mario Vargas Llosa</nombre>
            <fechaNacimiento>28/03/1936</fechaNacimiento>
        </autor>
        <fechaPublicacion>
            <anio>1972</anio>
        </fechaPublicacion>
    </libro>
    <libro>
        <titulo>Conversion en la catedral</titulo>
        <autor>
            <nombre>Mario Vargas Llosa</nombre>
            <fechaNacimiento>28/03/1936</fechaNacimiento>
        </autor>
        <fechaPublicacion>
            <anio>1969</anio>
        </fechaPublicacion>
    </libro>
</biblioteca>
